name: Cookiecutter template validation workflow

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
    - name: Check out src from GitHub
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        allow-softlinks: true
        auto-activate-base: false
        auto-update-conda: true
        channels: conda-forge
        channel-priority: flexible
        python-version: 3.8
        show-channel-urls: true
        use-only-tar-bz2: true
    - name: About conda
      run: |
        conda info
        conda list
        conda config --show
        conda config --show-sources
        conda config --set always_yes yes --set changeps1 no
    - name: Install dependencies
      run: |
        python3 -m pip install tox cookiecutter setuptools>=42 setuptools_scm wheel twine
        [ -f requirements.txt ] && python3 -m pip install -Ur requirements.txt
        [ -f test-requirements.txt ] && python3 -m pip install -Ur test-requirements.txt
        make bats-libraries
        echo "VERSION=$(python3 setup.py --version)"
    - name: Get variables
      id: get_vars
      run: |
        REPO=$(basename ${{ github.repository }})
        echo "REPO=${REPO}"
        echo ::set-output name=REPO::${REPO}

        BRANCH=${GITHUB_REF##*/}
        echo "BRANCH=${BRANCH}"
        echo ::set-output name=BRANCH::${BRANCH}

        VERSION=$(python3 setup.py --version 2>/dev/null)
        echo "VERSION=${VERSION}"
        echo ::set-output name=VERSION::${VERSION}

        TAG_VERSION=$(git describe --abbrev=0 --tags)
        echo "TAG_VERSION=${TAG_VERSION}"
        echo ::set-output name=TAG_VERSION::${TAG_VERSION}

        ARTIFACT="${REPO}-${BRANCH}"
        echo "ARTIFACT=${ARTIFACT}"
        echo ::set-output name=ARTIFACT::${REPO}-${BRANCH}
    - name: Generate example project
      run: |
        cookiecutter --no-input . package_name=example
    - name: Run tests
      run: |
        make test
